- name: Prepare host machine for yocto
  strategy: free
  hosts: localhost
  connection: local
  tasks:
    - name: Install required packages
      package:
        name:
          - gawk
          - wget
          - git-core
          - diffstat
          - unzip
          - texinfo
          - gcc-multilib
          - build-essential
          - chrpath
          - socat
          - cpio
          - python
          - python3
          - python3-pip
          - python3-pexpect
          - xz-utils
          - debianutils
          - iputils-ping
          - python3-git
          - python3-jinja2
          - libegl1-mesa
          - libsdl1.2-dev
          - pylint3
          - xterm
        state: latest
    
    - name: Ensure en_US.UTF-8 locale exists
      locale_gen:
        name: en_US.UTF-8
        state: present